name: Publish
on:
  push:
    branches: [main]
jobs:
  Dokka:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set Gradle properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: echo $GRADLE_PROPERTIES | base64 -d > ~/gradle.properties

      - name: Build documentation
        run: ./gradlew dokkaHtmlMultiModule

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build/dokka
  Maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set Gradle properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: echo $GRADLE_PROPERTIES | base64 -d > ~/gradle.properties

      - name: Maven Publish
        run: ./gradlew publish